GestionGimnasio/Controllers/ReporteGimnasiosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GestionGimnasio.Models;
using DinkToPdf;
using DinkToPdf.Contracts;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.Data.SqlClient;

namespace GestionGimnasio.Controllers
{
    public class ReporteGimnasiosController : Controller
    {
        private readonly IConverter _converter;

        private readonly GestionGimnasioContext _context;

        public ReporteGimnasiosController(IConverter converter, GestionGimnasioContext context)
        {
            _converter = converter;
            _context = context;
        }

        // GET: ReporteGimnasios
        public async Task<IActionResult> Index()
        {
            ViewData["ActivePage"] = "Gimnasios Reporte";
            ViewData["ActiveParent"] = "Reportes";

            ViewBag.PageTitle = "Gimnasios";
            return View();
        }


        //Vista de pdf
        public async Task<IActionResult> VistaParaPDF(string munic_Codigo)
        {
            var index = _context.tbGimnasios.Include(t => t.Munic_CodigoNavigation).Include(t => t.Usuar_CreacionNavigation).Include(t => t.Usuar_ModificacionNavigation).Where(t=>t.Gimna_Estado==true).OrderBy(t=>t.Munic_Codigo);
            return View("VistaParaPDF", await index.ToListAsync());
        }

        public IActionResult MostrarPDFenPagina()
        {
            string pagina_actual = HttpContext.Request.Path;
            string url_pagina = HttpContext.Request.GetEncodedUrl();
            url_pagina = url_pagina.Replace(pagina_actual, "");
            url_pagina = $"{url_pagina}/ReporteGimnasios/VistaParaPDF";


            var pdf = new HtmlToPdfDocument()
            {
                GlobalSettings = new GlobalSettings()
                {
                    PaperSize = PaperKind.A4,
                    Orientation = Orientation.Portrait
                },
                Objects = {
                    new ObjectSettings(){
                        Page = url_pagina
                    }
                }

            };

            var archivoPDF = _converter.Convert(pdf);
            return File(archivoPDF, "application/pdf");
        }

        public IActionResult DescargarPDF()
        {
            string pagina_actual = HttpContext.Request.Path;
            string url_pagina = HttpContext.Request.GetEncodedUrl();
            url_pagina = url_pagina.Replace(pagina_actual, "");
            url_pagina = $"{url_pagina}/ReporteGimnasios/VistaParaPDF";


            var pdf = new HtmlToPdfDocument()
            {
                GlobalSettings = new GlobalSettings()
                {
                    PaperSize = PaperKind.A4,
                    Orientation = Orientation.Portrait
                },
                Objects = {
                    new ObjectSettings(){
                        Page = url_pagina
                    }
                }

            };

            var archivoPDF = _converter.Convert(pdf);
            string nombrePDF = "Gimnasios_" + DateTime.Now.ToString("ddMMyyyyHHmmss") + ".pdf";

            return File(archivoPDF, "application/pdf", nombrePDF);
        }



        // GET: ReporteGimnasios/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tbGimnasios = await _context.tbGimnasios
                .Include(t => t.Munic_CodigoNavigation)
                .Include(t => t.Usuar_CreacionNavigation)
                .Include(t => t.Usuar_ModificacionNavigation)
                .FirstOrDefaultAsync(m => m.Gimna_Id == id);
            if (tbGimnasios == null)
            {
                return NotFound();
            }

            return View(tbGimnasios);
        }

        // GET: ReporteGimnasios/Create
        public IActionResult Create()
        {
            ViewData["Munic_Codigo"] = new SelectList(_context.tbMunicipios, "Munic_Codigo", "Munic_Codigo");
            ViewData["Usuar_Creacion"] = new SelectList(_context.tbUsuarios, "Usuar_id", "Usuar_Contrasena");
            ViewData["Usuar_Modificacion"] = new SelectList(_context.tbUsuarios, "Usuar_id", "Usuar_Contrasena");
            return View();
        }

        // POST: ReporteGimnasios/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Gimna_Id,Gimna_Nombre,Gimna_SemanaHoraApertura,Gimna_SemanaHoraCierre,Gimna_FinDeHoraApertura,Gimna_FinDeHoraCierre,Gimna_Direccion,Munic_Codigo,Gimna_Estado,Usuar_Creacion,Fecha_Creacion,Usuar_Modificacion,Fecha_Modificacion")] tbGimnasios tbGimnasios)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tbGimnasios);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Munic_Codigo"] = new SelectList(_context.tbMunicipios, "Munic_Codigo", "Munic_Codigo", tbGimnasios.Munic_Codigo);
            ViewData["Usuar_Creacion"] = new SelectList(_context.tbUsuarios, "Usuar_id", "Usuar_Contrasena", tbGimnasios.Usuar_Creacion);
            ViewData["Usuar_Modificacion"] = new SelectList(_context.tbUsuarios, "Usuar_id", "Usuar_Contrasena", tbGimnasios.Usuar_Modificacion);
            return View(tbGimnasios);
        }

        // GET: ReporteGimnasios/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tbGimnasios = await _context.tbGimnasios.FindAsync(id);
            if (tbGimnasios == null)
            {
                return NotFound();
            }
            ViewData["Munic_Codigo"] = new SelectList(_context.tbMunicipios, "Munic_Codigo", "Munic_Codigo", tbGimnasios.Munic_Codigo);
            ViewData["Usuar_Creacion"] = new SelectList(_context.tbUsuarios, "Usuar_id", "Usuar_Contrasena", tbGimnasios.Usuar_Creacion);
            ViewData["Usuar_Modificacion"] = new SelectList(_context.tbUsuarios, "Usuar_id", "Usuar_Contrasena", tbGimnasios.Usuar_Modificacion);
            return View(tbGimnasios);
        }

        // POST: ReporteGimnasios/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Gimna_Id,Gimna_Nombre,Gimna_SemanaHoraApertura,Gimna_SemanaHoraCierre,Gimna_FinDeHoraApertura,Gimna_FinDeHoraCierre,Gimna_Direccion,Munic_Codigo,Gimna_Estado,Usuar_Creacion,Fecha_Creacion,Usuar_Modificacion,Fecha_Modificacion")] tbGimnasios tbGimnasios)
        {
            if (id != tbGimnasios.Gimna_Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tbGimnasios);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!tbGimnasiosExists(tbGimnasios.Gimna_Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Munic_Codigo"] = new SelectList(_context.tbMunicipios, "Munic_Codigo", "Munic_Codigo", tbGimnasios.Munic_Codigo);
            ViewData["Usuar_Creacion"] = new SelectList(_context.tbUsuarios, "Usuar_id", "Usuar_Contrasena", tbGimnasios.Usuar_Creacion);
            ViewData["Usuar_Modificacion"] = new SelectList(_context.tbUsuarios, "Usuar_id", "Usuar_Contrasena", tbGimnasios.Usuar_Modificacion);
            return View(tbGimnasios);
        }

        // GET: ReporteGimnasios/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tbGimnasios = await _context.tbGimnasios
                .Include(t => t.Munic_CodigoNavigation)
                .Include(t => t.Usuar_CreacionNavigation)
                .Include(t => t.Usuar_ModificacionNavigation)
                .FirstOrDefaultAsync(m => m.Gimna_Id == id);
            if (tbGimnasios == null)
            {
                return NotFound();
            }

            return View(tbGimnasios);
        }

        // POST: ReporteGimnasios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tbGimnasios = await _context.tbGimnasios.FindAsync(id);
            if (tbGimnasios != null)
            {
                _context.tbGimnasios.Remove(tbGimnasios);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool tbGimnasiosExists(int id)
        {
            return _context.tbGimnasios.Any(e => e.Gimna_Id == id);
        }
    }
}

GestionGimnasio/Views/ReporteGimnasios/Index.cshtml
@model IEnumerable<GestionGimnasio.Models.tbGimnasios>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    Context.Session.SetString("titulo", "Reporte Gimnasios");
}
<div class="card">
    <div class="card-header" style="display:flex; justify-content:center">
        <a class="btn primary-button mx-2" asp-controller="ReporteGimnasios" asp-action="MostrarPDFenPagina" target="_blank">
            <span>
                <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 17v-5h1.5a1.5 1.5 0 1 1 0 3H5m12 2v-5h2m-2 3h2M5 10V7.914a1 1 0 0 1 .293-.707l3.914-3.914A1 1 0 0 1 9.914 3H18a1 1 0 0 1 1 1v6M5 19v1a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-1M10 3v4a1 1 0 0 1-1 1H5m6 4v5h1.375A1.627 1.627 0 0 0 14 15.375v-1.75A1.627 1.627 0 0 0 12.375 12H11Z" />
                </svg>
				Ver PDF
            </span>
        </a>
        <a class="btn primary-button mx-2" asp-controller="ReporteGimnasios" asp-action="DescargarPDF">
            <span>
                <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 13V4M7 14H5a1 1 0 0 0-1 1v4a1 1 0 0 0 1 1h14a1 1 0 0 0 1-1v-4a1 1 0 0 0-1-1h-2m-1-5-4 5-4-5m9 8h.01" />
                </svg>
                Descargar PDF
            </span>
        </a>        
    </div>
    <br />
    <div class="card-body" style="display:flex; justify-content:center">
        <div class="row">
            <embed src="@Url.Action("MostrarPDFenPagina","ReporteGimnasios")" width="1000" height="700" type="application/pdf" />
        </div>
    </div>
</div>

<script src="~/../js/core/jquery.3.2.1.min.js"></script>
<script src="~/../js/plugin/datatables/datatables.min.js"></script>
<script>
    $(document).ready(function(){
        $("#tablaIndex").DataTable();
    });
</script>

GestionGimnasio/Views/ReporteGimnasios/MostrarPDFenPagina.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>MostrarPDFenPagina</title>
</head>
<body>
</body>
</html>

GestionGimnasio/Views/ReporteGimnasios/VistaParaPDF.cshtml
@model IEnumerable<GestionGimnasio.Models.tbGimnasios>

@{
    ViewData["Title"] = "VistaParaPDF";
    Layout = null;
    int num=0;
    num++;
    string fecha = DateTime.Now.ToString("dd/MM/yyyy");
}
<link rel="stylesheet" href="~/../css/bootstrap.min.css">
<link rel="stylesheet" href="~/../css/atlantis.min.css">
<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
<div class="card">
    <div class="row">
        <h2 class="col-8">Reporte de Gimnasios</h2>
        <h2 class="col-2">@fecha</h2>
    </div>
    <div class="col-sm-12" style="display:block; justify-items:center">
        <img src="~/img/logo-login.png" alt="Logo" class="img-fluid" style="max-width: 12%;">
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-striped table-bordered" id="tablaIndex">
                <thead>
                    <tr>
                        <th>
                            Gimnasio
                        </th>
                        <th>
                            Municipio
                        </th>
                        <th>
                            Direccion
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Gimna_Nombre)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Munic_CodigoNavigation.Munic_Nombre)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Gimna_Direccion)
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    <footer class="footer" style="position:relative; top:860px">
        <div style="display:flex; justify-content:end">Pagina @num</div>
    </footer>
</div>